- name: Test Satellite
  hosts: localhost
  tasks:
    - name: Create Sample Organization
      redhat.satellite.organization:
        name: Test Organization
        state: present
        server_url: https://satellite.lab.example.com
        username: admin
        password: redhat
        validate_certs: no
