---
- name: Prepare Demos
  hosts: localhost
  vars_files: sat_vars.yml

  tasks:
    - name: Copy Red Hat Satellite Collections
      copy:
        src: Files/redhat-satellite-3.1.0.tar.gz
        dest: /tmp

    - name: Install and Update to Latest Ansible
      yum:
        name:  Files/ansible-2.9.15-1.el8ae.noarch.rpm
        state: latest
