- name: Test Satellite
  hosts: localhost
  vars_files: sat_vars.yml
  vars:
    org_name: My Org with Variable
  tasks:
    - name: Create Sample Organization
      redhat.satellite.organization:
        name: "{{ org_name }}"
        state: present
        server_url: "{{ sat_url }}"
        username: "{{ sat_un }}"
        password: "{{ sat_pw }}"
        validate_certs: "{{ cert_validate }}"
